import Head from "next/head";
import Header from "../components/Header";
import Nav from "../components/Nav";
import Results from "../components/Results";
import requests from "../utils/requests";

export default function Home({ results}) {
  console.log({results});
  return (
    <div>
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Nav />
      <Results results={results} />
    </div>
  );
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;
  const tryThis = `https://api.themoviedb.org/3/trending/all/week?api_key=${process.env.API_KEY}`;
  const url = `https://api.themoviedb.org/3${
    requests[genre]?.url || requests.fetchTrending.url
  }`;
  const request = await fetch(url);
  console.log("link: "+tryThis);
  const data = await request.json();
  return {
    props: {
      results: data.results,
    },
  };
}
